### PR TITLE
Fix sanitizing form elements

### LINKED ISSUE #14: Inputs are not sanitized
image

### PR DESCRIPTION
**Pull request by imaustink**
- Decode HTML entities before sanitization
- Added assertion for sanitized inputs

The inputs that are not getting sanitized are using HTML entities like `&lt;select&gt;`. To get around this, we decode the entities before sanitizing.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -46,7 +46,9 @@ describe("bitDocs.generators.searchMap",function(){
 		docMapPromise.then(function(docMap){
 			return searchMap(docMap, siteConfig);
 		}).then(function(searchMapResult){
-			assert.ok(searchMapResult['can-core'].description.indexOf('span') < 0);
+			var description = searchMapResult['can-core'].description;
+			assert.ok(description.indexOf('span') < 0, 'stripped basic HTML');
+			assert.ok(description.indexOf('input') < 0, 'stripped inputs');
```
Comment (chasenlehara) [inline test.js:51]: This tests for `input` but the `testDocMap` has `select`

Comment (imaustink) [reply test.js:51]: @chasenlehara fixed!

**Review by chasenlehara — APPROVED** [review]
The real test will be when we test it out in `bit-docs-html-canjs`…
